/**
 * The TradeLogger mark: a trade drawn the way the app draws trades (the
 * Position Track) — a red stop below, an entry, a path that rises to a target
 * line, and a dot where it lands. Same 64-unit geometry as the icon files in
 * brand/ (generated by brand/build_brand_assets.py); here the colours come
 * from theme tokens so the mark follows light and dark mode. See docs/BRAND.md.
 */
export function BrandMark({ size = 26 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 64 64" aria-hidden="true" focusable="false">
      <rect x="1" y="1" width="62" height="62" rx="14" fill="var(--tl-surface-elevated)" stroke="var(--tl-border)" strokeWidth="2" />
      <path d="M13 17.5H52" stroke="var(--tl-accent-fill)" strokeOpacity="0.45" strokeWidth="2.2" strokeLinecap="round" />
      <circle cx="48" cy="17.5" r="7.4" fill="var(--tl-surface-elevated)" />
      <path d="M11.5 49.5H23" stroke="var(--tl-negative)" strokeWidth="4" strokeLinecap="round" />
      <path d="M14 42 25 31 33 37.5 48 17.5" fill="none" stroke="var(--tl-accent-fill)" strokeWidth="4.6" strokeLinecap="round" strokeLinejoin="round" />
      <circle cx="48" cy="17.5" r="5" fill="var(--tl-accent-fill)" />
    </svg>
  )
}

export function BrandLockup({ compact = false }: { compact?: boolean }) {
  return (
    <span className="flex items-center gap-2.5">
      <BrandMark size={compact ? 22 : 26} />
      <span className="text-[14.5px] font-semibold tracking-[-0.015em] text-primary">TradeLogger</span>
    </span>
  )
}
